pipeline{
    agent any
    stages{
      stage('Clean'){
          steps{
          echo 'mvn clean'
          }
      }
      stage('Install'){
          steps{
          shell 'mvn install'
          }
      }
       stage('Deploy'){
          steps{
          shell 'mvn deploy'
          }
      }
    }
 }
